### ISSUE TITLE
Download not working 

### ISSUE THREAD

**Issue by DATL4G** [DATL4G/DXVKoTool#3]
Next issue, when i press on Download. It says "unknown error" and crashes with the following expection:

```
Exception in thread "DefaultDispatcher-worker-51" dev.datlag.dxvkotool.other.DownloadException$InvalidFile
        at dev.datlag.dxvkotool.other.DownloadException$InvalidFile.<clinit>(AppException.kt)
        at dev.datlag.dxvkotool.dxvk.DxvkStateCache$downloadCache$1$1.invokeSuspend(DxvkStateCache.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.awt.ComposeLayer$coroutineExceptionHandler$1@3d48bb99, androidx.compose.runtime.BroadcastFrameClock@6545033c, StandaloneCoroutine{Cancelling}@6ef87cf0, Dispatchers.IO]
```

_Originally posted by @YourSandwich in https://github.com/DATL4G/DXVKoTool/issues/2#issuecomment-1239102706_

**Comment by DATL4G** [comment]
@YourSandwich I need some information.

- On what game did you try the download
- what's the cache file name

**Comment by YourSandwich** [comment]
@DATL4G 

ApexLegends and the cache file is named "r5apex.dxvk-cache"
FallGuys worked even with merging
Ready or Not also did not work

**Comment by DATL4G** [comment]
@YourSandwich 

This issue are two separate issues.
I think I fixed the crash now.

Please pull the latest changes from the develop branch and test it.

I'm already working on the "second" issue, that Apex is not working

**Comment by DATL4G** [comment]
Apex Legends should work now as well

**Comment by YourSandwich** [comment]
It works <3 
I am super exited, now the open dialog looks also much better.
Wil be there also an option to export and merge own caches into the repositorie? This would be huge if this goes mainstream.

**Comment by DATL4G** [comment]
Alright the download works now properly.

The Ready or Not issue isn't related to this I think so please open another issue, with the same information I asked here.

Uploading caches to the repository may come, I can't tell at the moment.
I have to discuss this with the repository owner, however I'll make this production ready first before we have this discussion, and that's still a lot of work.

**Comment by DATL4G** [comment]
@YourSandwich 

When you create the issue please tell me on which button text the game hangs too.
I updated the develop branch to show more details about that.
